# Generated by Django 3.2.6 on 2021-09-05 18:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=250)),
                ('size', models.CharField(choices=[('T', 'tiny'), ('S', 'small'), ('M', 'medium'), ('L', 'large')], max_length=50)),
                ('friendliness', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('trainability', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('shedding_amount', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('exercise_needs', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=100)),
                ('favorite_food', models.CharField(max_length=120)),
                ('favorite_toy', models.CharField(max_length=120)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breed', to='api.breed')),
            ],
        ),
    ]
