# Generated by Django 3.2.6 on 2021-10-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='current_level',
            field=models.IntegerField(choices=[(1, 'level one'), (2, 'level two')], default=1),
        ),
    ]
