# Generated by Django 2.2 on 2021-09-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210906_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='modified_by',
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
