# Generated by Django 2.2 on 2021-10-06 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='images')),
                ('fb_profile', models.CharField(max_length=150)),
                ('twitter_profile', models.CharField(max_length=150)),
                ('linkedin_profile', models.CharField(max_length=150)),
                ('website', models.CharField(max_length=150)),
            ],
        ),
    ]
